### ISSUE TITLE
Fonts not working

### ISSUE THREAD

**Issue by henryruss3** [lukepolson/DiscordChatSimulator#3]
OSerror about fonts
I am on Windows 11

**Comment by henryruss2** [comment]
error message:
Traceback (most recent call last):
  File "c:\Users\Henry\Videos\DiscordChatSimulator-master\generate_chat.py", line 35, in <module>
    name_font = ImageFont.truetype('fonts/whitneymedium.otf', NAME_FONT_SIZE)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Henry\AppData\Roaming\Python\Python311\site-packages\PIL\ImageFont.py", line 976, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "C:\Users\Henry\AppData\Roaming\Python\Python311\site-packages\PIL\ImageFont.py", line 973, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Henry\AppData\Roaming\Python\Python311\site-packages\PIL\ImageFont.py", line 249, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource

**Comment by eesazahed** [comment]
I have this exact same issue!

@lukepolson I saw your youtube video and was interesting in using this service. Please solve this issue when you have time

**Comment by Syed-Taha-0** [comment]
It is not that fonts are not working, it is simply that the program looks for a folder named "fonts", in the same directory as the generate_chat.py file, and reads the font files from that folder. This folder is not supplied with the repository itself ( I imagine, due to licensing terms), you are to download those font files and put them in the said directory yourself. This should solve your issue!

**Comment by Syed-Taha-0** [comment]
> I have this exact same issue!
> 
> @lukepolson I saw your youtube video and was interesting in using this service. Please solve this issue when you have time
It is not that fonts are not working, it is simply that the program looks for a folder named "fonts", in the same directory as the generate_chat.py file, and reads the font files from that folder. This folder is not supplied with the repository itself ( I imagine, due to licensing terms), you are to download those font files and put them in the said directory yourself. This should solve your issue!

**Comment by diggingforce** [comment]
Go to the code folder where you put your code in and extract this zip file. Make sure the fonts (.oft) files are in the folder called fonts!, then it should work
[fonts.zip](https://github.com/lukepolson/DiscordChatSimulator/files/10302946/fonts.zip)

**Comment by henryruss2** [comment]
I fixed it in my PR #4

**Comment by eesazahed** [comment]
@henryruss2 thanks, it looks good

**Comment by henryruss3** [comment]
Merge, please

**Comment by lukepolson** [comment]
MErged
